### ISSUE TITLE
iOS集成编译不通过 Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by yshiliang** [TencentCloud/cos-sdk-react-native-plugin#1]
编译报错提示如下：
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ImageCropPicker", referenced from:
      objc-class-ref in ImageCropPicker+HOOK.o
      __OBJC_$_CATEGORY_ImageCropPicker_$_HOOK in ImageCropPicker+HOOK.o
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      _OBJC_CLASS_$_STEventEmitter in STEventEmitter.o
  "_OBJC_CLASS_$_RNSplashScreen", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SSZipArchive", referenced from:
      objc-class-ref in STUpgradeAppManager.o
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_STEventEmitter in STEventEmitter.o
  "_RCTAppSetupDefaultRootView", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_RCTAppSetupPrepareApp", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_RCTRegisterModule", referenced from:
      +[STImageCompressManager load] in STImageCompressManager.o
      +[STEventEmitter load] in STEventEmitter.o
      +[STUpgradeAppManager load] in STUpgradeAppManager.o
      +[STConfigManager load] in STConfigManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

已经加入了-all_load
RN版本：0.70.7

**Comment by jordanqin** [comment]
麻烦更新最新版本，并用我们的demo进行编译 https://github.com/TencentCloud/cos-sdk-react-native-plugin/tree/main/example。
如果还有问题，麻烦描述本地编译环境以及rn版本等（这种问题一般属于通用的RN问题，并非SDK问题）
