### ISSUE TITLE
No visible @interface for 'QCloudCOSXMLUploadObjectRequest' declares the selector 'uploadid'

### ISSUE THREAD

**Issue by devyu** [TencentCloud/cos-sdk-react-native-plugin#2]
SDK不是最新的吗？提示找不到uploadid

**Comment by devyu** [comment]
<img width="1089" alt="截屏2023-07-12 上午11 40 07" src="https://github.com/TencentCloud/cos-sdk-react-native-plugin/assets/15952780/3704c122-9b2a-49ba-ada8-e856ff78938c">

**Comment by devyu** [comment]
<img width="1050" alt="截屏2023-07-12 上午11 40 53" src="https://github.com/TencentCloud/cos-sdk-react-native-plugin/assets/15952780/50e6823f-5ba8-48b5-a03c-a390c33da8de">

**Comment by jordanqin** [comment]
@devyu 
由于iOS SDK发布新版本删掉了uploadid字段， react native依赖新版iOS sdk时会出现上述问题。
已经发布了 react native sdk 1.0.3版本，修复iOS新版本依赖uploadid字段缺失问题。
麻烦更新下sdk版本，感谢感谢
