### ISSUE TITLE
在 arm 芯片上构建失败，Excluded Architectures arm64 

### ISSUE THREAD

**Issue by onlyling** [TencentCloud/cos-sdk-react-native-plugin#5]
## 系统

- macOS 14.4.1
- Xcode 15.3 
- 芯片 Apple M1 Pro
- react-native 0.73.6
- react-native-cos-sdk 1.0.9

## 影响

react-native-cos-sdk 以及依赖的 QCloudCOSXML 都有配置 `Excluded Architectures arm64`，在最后构建出错。

或许把这几个库的 `project.pbxproj` 里面的 `"EXCLUDED_ARCHS[sdk=*]" = arm64;` 删了可以解决。

<img width="668" alt="image" src="https://github.com/TencentCloud/cos-sdk-react-native-plugin/assets/9999765/3515a23d-481e-41dd-934d-077e6d23b556">

## 有误 pod

<img width="807" alt="image" src="https://github.com/TencentCloud/cos-sdk-react-native-plugin/assets/9999765/17d23e35-a1a1-455a-8f21-92be6b9b73cc">

## 项目信息

<img width="897" alt="image" src="https://github.com/TencentCloud/cos-sdk-react-native-plugin/assets/9999765/62094ff9-280f-468b-bd5b-46f7f52a5a0b">

## 其他 pod

<img width="917" alt="image" src="https://github.com/TencentCloud/cos-sdk-react-native-plugin/assets/9999765/0c2159b6-98ef-4fd4-b3d7-b1d410ff9d1b">

**Comment by jordanqin** [comment]
@onlyling 我们这边用Apple M系列构建是没问题的，建议升级到最新的cos sdk并参考example项目排查
