### ISSUE TITLE
[help] 在最新的 expo 上启动失败

### ISSUE THREAD

**Issue by songispm** [TencentCloud/cos-sdk-react-native-plugin#8]
Expo项目，使用 expo run:ios 启动，并不是 Expo Go

newArchEnabled: true
<img width="1874" alt="image" src="https://github.com/user-attachments/assets/c9d184f5-c9ec-4c6c-a262-06ee2491203a">

newArchEnabled: false
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/40592689-9a66-456c-a5de-8167f1fc3691">

m1 arm平台，为什么显式 x86_64

**Comment by jordanqin** [comment]
@songispm 目前rn cos sdk还不支持newArchEnabled。
newArchEnabled: false时的报错看起来并不是rn cos sdk报的。
