### ISSUE TITLE
XCode16编译报错 Declaration of 'sa_family_t' must be imported

### ISSUE THREAD

**Issue by davistsin** [TencentCloud/cos-sdk-react-native-plugin#9]
发生在
QCloudCore/Default/QCloudSimplePing.h

82行
```h
@property (nonatomic, assign, readonly) sa_family_t hostAddressFamily;
```
Declaration of 'sa_family_t' must be imported from module 'Darwin.POSIX.sys.types._sa_family_t' before it is required

---

#import <sys/_types/_sa_family_t.h>

**Comment by jordanqin** [comment]
@davistsin 您使用的版本是多少呢？新版本1.1.5已经解决了该问题，麻烦升级一下
